### ISSUE TITLE
problem with running package

### ISSUE THREAD

**Issue by ketchup007** [RobotnikAutomation/rbkairos_common#2]
after package instalaction (kinetic-devel) and running:
`/opt/ros/kinetic/lib/xacro/xacro '/home/ketchup/catkin_simulation_ws/src/rbkairos_common/rbkairos_description/robots/rbkairos_ur10.urdf.xacro' prefix:=robot_ ros_planar_move_plugin:=true load_kinematics_file:=true --inorder`

get result:
```
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://wiki.ros.org/xacro
 new: http://www.ros.org/wiki/xacro (/opt/ros/kinetic/share/robotnik_sensors/urdf/all_sensors.urdf.xacro)
Invalid parameter "kinematics_file" None None
when instantiating macro: ur10_robot (/opt/ros/kinetic/share/ur_description/urdf/ur10.urdf.xacro)
instantiated from: rbkairos (/home/ketchup/catkin_simulation_ws/src/rbkairos_common/rbkairos_description/robots/rbkairos_ur10.urdf.xacro)
in file: /home/ketchup/catkin_simulation_ws/src/rbkairos_common/rbkairos_description/robots/rbkairos_ur10.urdf.xacro
```
There are is no documentation about kinematics_file.

**Comment by RomanRobotnik** [comment]
Hi,

I've updated [rbkairos_sim](https://github.com/RobotnikAutomation/rbkairos_sim/commit/bcd430e013054d3df81ab79530d9597adaa199da) to fix this issue. 

The option of loading the "kinematics_file" in the "urdf" of the arm is now available to work with the official ROS driver from Universal Robot that uses this [repo](https://github.com/fmauch/universal_robot.git) as ur_description. This new driver requires a configuration created for each specific arm. 

Our description files allow either using or not this new ur_description.
By default, in the simulation, the flag that let us choose was as true, and that's why it fails.

With the new update, the flag is false by default, and it will be compatible with the standard ur5 urdf.
